# Generated by Django 3.2.2 on 2021-05-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='report',
            name='remarks',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
